server:
  port: 8082
  servlet:
    context-path: /portfolio-service

spring:
  application:
    name: portfolio-service
  
  # Database configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.h2.Driver
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console

# Portfolio service configuration
portfolio:
  cache:
    enabled: true
    type: memory # REVIEW: caching vs direct lookup - can be changed to redis or database
    ttl: 300000 # 5 minutes in milliseconds
  pnl:
    calculation:
      precision: 2 # decimal places for P&L calculations
    validation:
      enabled: true
      max-quantity: 1000000
      max-price: 1000000

# Price cache configuration
price-cache:
  enabled: true
  type: memory # REVIEW: caching vs direct lookup - implement Redis/DB cache interface
  mock-prices:
    enabled: true
    symbols:
      - AAPL
      - GOOGL
      - MSFT
      - TSLA
      - AMZN
      - BTC-USD
      - ETH-USD

# Logging configuration
logging:
  level:
    com.fintech.portfolio: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

# Application specific configuration
app:
  name: Portfolio Service
  version: 1.0.0
  description: Portfolio management service with P&L calculation
